### ISSUE TITLE
Trata de borrar esto chamo

### ISSUE THREAD

**Issue by cmp831** [leolivares/leolivares#4]
@milanialejandro

**Comment by milanialejandro** [comment]
Hey khe weá

**Comment by cmp831** [comment]
@milanialejandro

**Comment by cmp831** [comment]
@milanialejandro

**Comment by cmp831** [comment]
- [ ] Tickeas esto si eres gay

**Comment by cmp831** [comment]
@leolivares ya veo que tickeaste eso 

> * [ ]  Tickeas esto si eres gay
